const theme = {
  useBorderBox: true,
  useSmoothScroll: true,
  sizes: {
    body: 1120,
    header: 70,
    footer: 100,
    minGlobal: 'calc(100vh - 100.1px)',
    min: 'calc(100vh - 170.1px)',
  },
  fonts: {
    body: 'Ubuntu, sans-serif',
    heading: 'Ubuntu, sans-serif',
  },
  fontWeights: {
    body: '400',
    heading: '700',
    bold: '700',
  },
  radii: [ 3 ],
  breakpoints: [ '832px' ],
  space: [ 0, 4, 8, 16, 32, 64, 128, 256, 512 ],
  fontSizes: [ 13, 14, 16, 20, 24, 32, 48, 64, 96 ],
  shadows: {
    low: '0 0 0 1px rgb(136 152 170 / 10%), 0 10px 20px 0 rgb(49 49 93 / 8%), 0 3px 10px 0 rgb(0 0 0 / 5%)',
    hover: '0 14px 28px rgba(0,0,0,0.25), 0 10px 10px rgba(0,0,0,0.22)',
    high: '0 0 0 1px rgb(136 152 170 / 10%), 0 15px 35px 0 rgb(49 49 93 / 10%), 0 5px 15px 0 rgb(0 0 0 / 8%)',
  },
  lineHeights: {
    body: 1.2,
    heading: 1.125,
  },
  letterSpacings: {
    body: 0.5,
    heading: -0.5,
  },
  colors: {
    text: 'rgb(2, 0, 75)',
    textLight: '#565656',
    background: '#f4f5f5',
    primary: 'rgb(89, 130, 235)',
    accent: '#FF4D4D',
  },
  text: {
    heading: {
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'heading',
      letterSpacing: 'heading',
    },
    body: {
      fontFamily: 'body',
      lineHeight: 'body',
      letterSpacing: 'body',
    },
    light: {
      fontFamily: 'body',
      lineHeight: 'body',
      letterSpacing: 'body',
      color: 'textLight',
    },
  },
  styles: {
    root: {
      listStyle: 'none',
      backgroundColor: 'background',
      fontFamily: 'body',
      lineHeight: 'body',
      fontWeight: 'body',
      letterSpacing: 'body',
    },
  },
  Button: {
    primary: {
      variant: 'text.body',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      width: 'fit-content',
      height: '30px',
      textAlign: 'center',
      cursor: 'pointer',
      color: 'white',
      bg: 'primary',
      borderRadius: '2px',
      border: 'none',
      px: 3,
      fontSize: 2,
      '&:focus': { outline: 'none' },
    },
    primaryAlternate: {
      default: {
        variant: 'Button.primary',
        bg: 'text',
        borderRadius: '50px',
        fontSize: 2,
        position: 'relative',
        pr: '25px',
        '&:hover': { filter: 'brightness(90%)' },
        '&::after': {
          height: '10px',
          content: 'url(/rightArrayCTA.svg)',
          position: 'absolute',
          right: '10px',
          top: 'calc(50% - 8.5px)',
          transition: 'transform 0.1s ease',
        },
        '&:hover::after': { transform: 'translateX(5px)' },
        '&:hover::before': {
          content: 'url(/rightArrayCTA--dash.svg)',
          height: '10px',
          display: 'flex',
          alignItems: 'center',
          position: 'absolute',
          right: '8px',
          top: 'calc(50% - 8.5px)',
        },
      },
      M: {
        variant: 'Button.primaryAlternate.default',
      },
      S: {
        variant: 'Button.primaryAlternate.default',
        fontSize: 1,
        px: 2,
        pr: '20px',
        height: '25px',
        '&::after': {
          height: '10px',
          content: 'url(/rightArrayCTA.svg)',
          position: 'absolute',
          right: '8px',
          top: 'calc(50% - 6px)',
          transition: 'transform 0.1s ease',
        },
        '&:hover::before': {
          content: 'url(/rightArrayCTA--dash.svg)',
          height: '10px',
          display: 'flex',
          alignItems: 'center',
          position: 'absolute',
          right: '6px',
          top: 'calc(50% - 8.5px)',
        },
      },
    },
  },
  Input: { // Editable text field
    hBold: {
      variant: 'text.body',
      fontSize: 4,
      fontWeight: 'bold',
      my: 3,
    },
    h: {
      variant: 'text.body',
      fontSize: 4,
      py: 1,
    },
    regular: {
      variant: 'text.body',
      fontSize: 2,
    },
    light: {
      variant: 'text.light',
      fontSize: 0,
    },
    bold: {
      variant: 'text.body',
      fontWeight: '600',
      fontsize: 2,
    },
  },
  Card: {
    default: {
      display: 'flex',
      flexDirection: 'column',
      width: 250,
      height: 320,
      bg: 'white',
      border: '1px solid lightgrey',
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: '3px',
      cursor: 'pointer',
      position: 'relative',
      transition: 'box-shadow 0.3s ease-in-out',
      '&:hover': { boxShadow: 'high' },
    },
    active: {
      variant: 'Card.default',
      border: '2px solid',
      borderColor: 'primary',
      boxShadow: 'low',
      mb: '70px !important',
      '&::after': {
        content: '"active"',
        width: '100%',
        bg: 'primary',
        color: 'white',
        textAlign: 'center',
        position: 'absolute',
        bottom: 0,
      },
      '&::before': {
        content: '"Votre QR Code renvoie vos clients vers cette carte."',
        position: 'absolute',
        bottom: '-50px',
      },
    },
    empty: {
      variant: 'Card.default',
      border: '2px solid',
      borderColor: 'primary',
      bg: 'transparent',
    },
  },
  Product: {
    //! Category height calculated on product height. If you have to change, DON'T FORGET to change the equation in Category. Bitch.
    desktop: {
      borderRadius: 0,
      height: '120px',
      overflow: 'hidden',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'space-between',
      padding: 2,
    },
  },
}

export default theme
